version: '3.8'

services:
  pdf-extractor:
    build: .
    container_name: header_extractor
    volumes:
      - ./input:/app/input:ro
      - ./Collection 1:/app/Collection 1
      - ./gemma3-1b-it-int4.task:/app/gemma3-1b-it-int4.task:ro
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app
    command: python solution.py
